# docker-compose.yml
version: '3'
services:
  database:
    container_name: database
    build: ./database
    ports:
      - "5432:5432"
  network-config-server:
    container_name: network-config-server
    build: ./network-config-server
    ports:
      - "8888:8888"
  network-discovery-server:
    container_name: network-discovery-server
    build: ./network-discovery-server
    ports:
      - "8761:8761"
  network-users:
    container_name: network-users
    build: ./network-users
    ports:
      - "8081:8081"
  network-posts:
    container_name: network-posts
    build: ./network-posts
    ports:
      - "8082:8082"
  network-messages:
    container_name: network-messages
    build: ./network-messages
    ports:
      - "8083:8083"