spring:
  datasource:
    url: jdbc:postgresql://database:5432/network
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://network-discovery-server:8761/eureka/